# Generated by Django 5.0.4 on 2024-05-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('PERSONAL_LOAN', 'PERSONAL_LOAN'), ('HOME_LOAN', 'HOME_LOAN'), ('CAR_LOAN', 'CAR_LOAN'), ('EDUCATION_LOAN', 'EDUCATION_LOAN')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=8.5, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
